/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package Lab1;

public class Library {
	
	// Step 3.1
	public static void main(String[] a) {
		Library lib = new Library();
		if (lib.someLibraryMethod())
			System.out.println("When there is a fire, commit and push.");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
