/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package Lab1;

public class Library {
	
	// Step 1.6
	public static void main(String[] a) {
		System.out.println("When there is a fire, commit and push.");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
